from __future__ import annotations

# ISO 639-3 language reference data used by the seed script.
LANGUAGES = [{'code': 'aar', 'name': 'Afar', 'native_name': 'Afar', 'is_rtl': False},
 {'code': 'abk', 'name': 'Abkhazian', 'native_name': 'Аҧсуа', 'is_rtl': False},
 {'code': 'afr', 'name': 'Afrikaans', 'native_name': 'Afrikaans', 'is_rtl': False},
 {'code': 'aka', 'name': 'Akan', 'native_name': 'Akan', 'is_rtl': False},
 {'code': 'akk', 'name': 'Akkadian', 'native_name': None, 'is_rtl': False},
 {'code': 'amh', 'name': 'Amharic', 'native_name': 'አማርኛ', 'is_rtl': False},
 {'code': 'ara', 'name': 'Arabic', 'native_name': 'العربية', 'is_rtl': True},
 {'code': 'arc', 'name': 'Imperial Aramaic', 'native_name': '𐡀𐡓𐡌𐡉𐡀', 'is_rtl': True},
 {'code': 'arg', 'name': 'Aragonese', 'native_name': 'Aragonés', 'is_rtl': False},
 {'code': 'asm', 'name': 'Assamese', 'native_name': 'অসমীয়া', 'is_rtl': False},
 {'code': 'ava', 'name': 'Avaric', 'native_name': 'Авар мацӀ', 'is_rtl': False},
 {'code': 'ave', 'name': 'Avestan', 'native_name': 'Avesta', 'is_rtl': False},
 {'code': 'aym', 'name': 'Aymara', 'native_name': 'Aymar aru', 'is_rtl': False},
 {'code': 'aze', 'name': 'Azerbaijani', 'native_name': 'Azərbaycanca', 'is_rtl': False},
 {'code': 'bak', 'name': 'Bashkir', 'native_name': 'Башҡортса', 'is_rtl': False},
 {'code': 'bam', 'name': 'Bambara', 'native_name': 'Bamanankan', 'is_rtl': False},
 {'code': 'bel', 'name': 'Belarusian', 'native_name': 'Беларуская', 'is_rtl': False},
 {'code': 'ben', 'name': 'Bengali', 'native_name': 'বাংলা', 'is_rtl': False},
 {'code': 'bho', 'name': 'Bhojpuri', 'native_name': 'भोजपुरी', 'is_rtl': False},
 {'code': 'bis', 'name': 'Bislama', 'native_name': 'Bislama', 'is_rtl': False},
 {'code': 'bod', 'name': 'Tibetan', 'native_name': 'བོད་ཡིག', 'is_rtl': False},
 {'code': 'bos', 'name': 'Bosnian', 'native_name': 'Bosanski', 'is_rtl': False},
 {'code': 'bre', 'name': 'Breton', 'native_name': 'Brezhoneg', 'is_rtl': False},
 {'code': 'bul', 'name': 'Bulgarian', 'native_name': 'Български', 'is_rtl': False},
 {'code': 'cat', 'name': 'Catalan', 'native_name': 'Català', 'is_rtl': False},
 {'code': 'ces', 'name': 'Czech', 'native_name': 'Čeština', 'is_rtl': False},
 {'code': 'cha', 'name': 'Chamorro', 'native_name': 'Chamoru', 'is_rtl': False},
 {'code': 'che', 'name': 'Chechen', 'native_name': 'Нохчийн мотт', 'is_rtl': False},
 {'code': 'chu', 'name': 'Church Slavic', 'native_name': 'Словѣньскъ', 'is_rtl': False},
 {'code': 'chv', 'name': 'Chuvash', 'native_name': 'Чӑвашла', 'is_rtl': False},
 {'code': 'cor', 'name': 'Cornish', 'native_name': 'Kernewek', 'is_rtl': False},
 {'code': 'cos', 'name': 'Corsican', 'native_name': 'Corsu', 'is_rtl': False},
 {'code': 'cre', 'name': 'Cree', 'native_name': 'ᓀᐦᐃᔭᐍᐏᐣ', 'is_rtl': False},
 {'code': 'cym', 'name': 'Welsh', 'native_name': 'Cymraeg', 'is_rtl': False},
 {'code': 'dan', 'name': 'Danish', 'native_name': 'Dansk', 'is_rtl': False},
 {'code': 'deu', 'name': 'German', 'native_name': 'Deutsch', 'is_rtl': False},
 {'code': 'div', 'name': 'Divehi', 'native_name': 'ދިވެހި', 'is_rtl': True},
 {'code': 'dzo', 'name': 'Dzongkha', 'native_name': 'རྫོང་ཁ', 'is_rtl': False},
 {'code': 'egy', 'name': 'Egyptian (Ancient)', 'native_name': None, 'is_rtl': False},
 {'code': 'ell', 'name': 'Modern Greek', 'native_name': 'Ελληνικά', 'is_rtl': False},
 {'code': 'eng', 'name': 'English', 'native_name': 'English', 'is_rtl': False},
 {'code': 'epo', 'name': 'Esperanto', 'native_name': 'Esperanto', 'is_rtl': False},
 {'code': 'est', 'name': 'Estonian', 'native_name': 'Eesti', 'is_rtl': False},
 {'code': 'eus', 'name': 'Basque', 'native_name': 'Euskara', 'is_rtl': False},
 {'code': 'ewe', 'name': 'Ewe', 'native_name': 'Eʋegbe', 'is_rtl': False},
 {'code': 'fao', 'name': 'Faroese', 'native_name': 'Føroyskt', 'is_rtl': False},
 {'code': 'fas', 'name': 'Persian', 'native_name': 'فارسی', 'is_rtl': True},
 {'code': 'fij', 'name': 'Fijian', 'native_name': 'Na Vosa Vakaviti', 'is_rtl': False},
 {'code': 'fin', 'name': 'Finnish', 'native_name': 'Suomi', 'is_rtl': False},
 {'code': 'fra', 'name': 'French', 'native_name': 'Français', 'is_rtl': False},
 {'code': 'fry', 'name': 'Western Frisian', 'native_name': 'Frysk', 'is_rtl': False},
 {'code': 'ful', 'name': 'Fulah', 'native_name': 'Fulfulde', 'is_rtl': False},
 {'code': 'gla', 'name': 'Scottish Gaelic', 'native_name': 'Gàidhlig', 'is_rtl': False},
 {'code': 'gle', 'name': 'Irish', 'native_name': 'Gaeilge', 'is_rtl': False},
 {'code': 'glg', 'name': 'Galician', 'native_name': 'Galego', 'is_rtl': False},
 {'code': 'glv', 'name': 'Manx', 'native_name': 'Gaelg', 'is_rtl': False},
 {'code': 'grc', 'name': 'Ancient Greek', 'native_name': 'Ἑλληνική', 'is_rtl': False},
 {'code': 'grn', 'name': 'Guarani', 'native_name': "Avañe'ẽ", 'is_rtl': False},
 {'code': 'guj', 'name': 'Gujarati', 'native_name': 'ગુજરાતી', 'is_rtl': False},
 {'code': 'hat', 'name': 'Haitian Creole', 'native_name': 'Kreyòl ayisyen', 'is_rtl': False},
 {'code': 'hau', 'name': 'Hausa', 'native_name': 'Hausa', 'is_rtl': False},
 {'code': 'heb', 'name': 'Hebrew', 'native_name': 'עברית', 'is_rtl': True},
 {'code': 'her', 'name': 'Herero', 'native_name': 'Otjiherero', 'is_rtl': False},
 {'code': 'hin', 'name': 'Hindi', 'native_name': 'हिन्दी', 'is_rtl': False},
 {'code': 'hmo', 'name': 'Hiri Motu', 'native_name': 'Hiri Motu', 'is_rtl': False},
 {'code': 'hrv', 'name': 'Croatian', 'native_name': 'Hrvatski', 'is_rtl': False},
 {'code': 'hun', 'name': 'Hungarian', 'native_name': 'Magyar', 'is_rtl': False},
 {'code': 'hye', 'name': 'Armenian', 'native_name': 'Հայերեն', 'is_rtl': False},
 {'code': 'ibo', 'name': 'Igbo', 'native_name': 'Igbo', 'is_rtl': False},
 {'code': 'ido', 'name': 'Ido', 'native_name': 'Ido', 'is_rtl': False},
 {'code': 'iii', 'name': 'Sichuan Yi', 'native_name': 'ꆈꌠꉙ', 'is_rtl': False},
 {'code': 'iku', 'name': 'Inuktitut', 'native_name': 'ᐃᓄᒃᑎᑐᑦ', 'is_rtl': False},
 {'code': 'ile', 'name': 'Interlingue', 'native_name': 'Interlingue', 'is_rtl': False},
 {'code': 'ina', 'name': 'Interlingua', 'native_name': 'Interlingua', 'is_rtl': False},
 {'code': 'ind', 'name': 'Indonesian', 'native_name': 'Bahasa Indonesia', 'is_rtl': False},
 {'code': 'ipk', 'name': 'Inupiaq', 'native_name': 'Iñupiaq', 'is_rtl': False},
 {'code': 'isl', 'name': 'Icelandic', 'native_name': 'Íslenska', 'is_rtl': False},
 {'code': 'ita', 'name': 'Italian', 'native_name': 'Italiano', 'is_rtl': False},
 {'code': 'jav', 'name': 'Javanese', 'native_name': 'Basa Jawa', 'is_rtl': False},
 {'code': 'jpn', 'name': 'Japanese', 'native_name': '日本語', 'is_rtl': False},
 {'code': 'kal', 'name': 'Kalaallisut', 'native_name': 'Kalaallisut', 'is_rtl': False},
 {'code': 'kan', 'name': 'Kannada', 'native_name': 'ಕನ್ನಡ', 'is_rtl': False},
 {'code': 'kas', 'name': 'Kashmiri', 'native_name': 'कश्मीरी', 'is_rtl': False},
 {'code': 'kat', 'name': 'Georgian', 'native_name': 'ქართული', 'is_rtl': False},
 {'code': 'kau', 'name': 'Kanuri', 'native_name': 'Kanuri', 'is_rtl': False},
 {'code': 'kaz', 'name': 'Kazakh', 'native_name': 'Қазақ тілі', 'is_rtl': False},
 {'code': 'khm', 'name': 'Khmer', 'native_name': 'ខ្មែរ', 'is_rtl': False},
 {'code': 'kik', 'name': 'Kikuyu', 'native_name': 'Gĩkũyũ', 'is_rtl': False},
 {'code': 'kin', 'name': 'Kinyarwanda', 'native_name': 'Ikinyarwanda', 'is_rtl': False},
 {'code': 'kir', 'name': 'Kirghiz', 'native_name': 'Кыргызча', 'is_rtl': False},
 {'code': 'kom', 'name': 'Komi', 'native_name': 'Коми', 'is_rtl': False},
 {'code': 'kon', 'name': 'Kongo', 'native_name': 'Kikongo', 'is_rtl': False},
 {'code': 'kor', 'name': 'Korean', 'native_name': '한국어', 'is_rtl': False},
 {'code': 'kua', 'name': 'Kuanyama', 'native_name': 'Kuanyama', 'is_rtl': False},
 {'code': 'kur', 'name': 'Kurdish', 'native_name': 'Kurdî', 'is_rtl': False},
 {'code': 'lao', 'name': 'Lao', 'native_name': 'ລາວ', 'is_rtl': False},
 {'code': 'lat', 'name': 'Latin', 'native_name': 'Latina', 'is_rtl': False},
 {'code': 'lav', 'name': 'Latvian', 'native_name': 'Latviešu', 'is_rtl': False},
 {'code': 'lim', 'name': 'Limburgish', 'native_name': 'Limburgs', 'is_rtl': False},
 {'code': 'lin', 'name': 'Lingala', 'native_name': 'Lingála', 'is_rtl': False},
 {'code': 'lit', 'name': 'Lithuanian', 'native_name': 'Lietuvių', 'is_rtl': False},
 {'code': 'ltz', 'name': 'Luxembourgish', 'native_name': 'Lëtzebuergesch', 'is_rtl': False},
 {'code': 'lub', 'name': 'Luba-Katanga', 'native_name': 'Tshiluba', 'is_rtl': False},
 {'code': 'lug', 'name': 'Ganda', 'native_name': 'Luganda', 'is_rtl': False},
 {'code': 'mah', 'name': 'Marshallese', 'native_name': 'Kajin M̧ajeļ', 'is_rtl': False},
 {'code': 'mal', 'name': 'Malayalam', 'native_name': 'മലയാളം', 'is_rtl': False},
 {'code': 'mar', 'name': 'Marathi', 'native_name': 'मराठी', 'is_rtl': False},
 {'code': 'mkd', 'name': 'Macedonian', 'native_name': 'Македонски', 'is_rtl': False},
 {'code': 'mlg', 'name': 'Malagasy', 'native_name': 'Malagasy', 'is_rtl': False},
 {'code': 'mlt', 'name': 'Maltese', 'native_name': 'Malti', 'is_rtl': False},
 {'code': 'mon', 'name': 'Mongolian', 'native_name': 'Монгол', 'is_rtl': False},
 {'code': 'mri', 'name': 'Maori', 'native_name': 'Māori', 'is_rtl': False},
 {'code': 'msa', 'name': 'Malay', 'native_name': 'Bahasa Melayu', 'is_rtl': False},
 {'code': 'mya', 'name': 'Burmese', 'native_name': 'မြန်မာဘာသာ', 'is_rtl': False},
 {'code': 'nau', 'name': 'Nauru', 'native_name': 'Dorerin Naoero', 'is_rtl': False},
 {'code': 'nav', 'name': 'Navajo', 'native_name': 'Diné bizaad', 'is_rtl': False},
 {'code': 'nbl', 'name': 'South Ndebele', 'native_name': 'IsiNdebele', 'is_rtl': False},
 {'code': 'nde', 'name': 'North Ndebele', 'native_name': 'IsiNdebele', 'is_rtl': False},
 {'code': 'ndo', 'name': 'Ndonga', 'native_name': 'Owambo', 'is_rtl': False},
 {'code': 'nep', 'name': 'Nepali', 'native_name': 'नेपाली', 'is_rtl': False},
 {'code': 'nld', 'name': 'Dutch', 'native_name': 'Nederlands', 'is_rtl': False},
 {'code': 'nno', 'name': 'Norwegian Nynorsk', 'native_name': 'Norsk nynorsk', 'is_rtl': False},
 {'code': 'nob', 'name': 'Norwegian Bokmål', 'native_name': 'Norsk bokmål', 'is_rtl': False},
 {'code': 'nor', 'name': 'Norwegian', 'native_name': 'Norsk', 'is_rtl': False},
 {'code': 'nya', 'name': 'Chichewa', 'native_name': 'Chichewa', 'is_rtl': False},
 {'code': 'oci', 'name': 'Occitan', 'native_name': 'Occitan', 'is_rtl': False},
 {'code': 'oji', 'name': 'Ojibwa', 'native_name': 'Ojibwe', 'is_rtl': False},
 {'code': 'ori', 'name': 'Oriya', 'native_name': 'ଓଡ଼ିଆ', 'is_rtl': False},
 {'code': 'orm', 'name': 'Oromo', 'native_name': 'Afaan Oromoo', 'is_rtl': False},
 {'code': 'oss', 'name': 'Ossetian', 'native_name': 'Ирон æвзаг', 'is_rtl': False},
 {'code': 'pan', 'name': 'Panjabi', 'native_name': 'ਪੰਜਾਬੀ', 'is_rtl': False},
 {'code': 'pli', 'name': 'Pali', 'native_name': 'पालि', 'is_rtl': False},
 {'code': 'pol', 'name': 'Polish', 'native_name': 'Polski', 'is_rtl': False},
 {'code': 'por', 'name': 'Portuguese', 'native_name': 'Português', 'is_rtl': False},
 {'code': 'pus', 'name': 'Pashto', 'native_name': 'پښتو', 'is_rtl': True},
 {'code': 'que', 'name': 'Quechua', 'native_name': 'Runa Simi', 'is_rtl': False},
 {'code': 'roh', 'name': 'Romansh', 'native_name': 'Rumantsch', 'is_rtl': False},
 {'code': 'ron', 'name': 'Romanian', 'native_name': 'Română', 'is_rtl': False},
 {'code': 'run', 'name': 'Rundi', 'native_name': 'Ikirundi', 'is_rtl': False},
 {'code': 'rus', 'name': 'Russian', 'native_name': 'Русский', 'is_rtl': False},
 {'code': 'sag', 'name': 'Sango', 'native_name': 'Sängö', 'is_rtl': False},
 {'code': 'san', 'name': 'Sanskrit', 'native_name': 'संस्कृतम्', 'is_rtl': False},
 {'code': 'sin', 'name': 'Sinhala', 'native_name': 'සිංහල', 'is_rtl': False},
 {'code': 'slk', 'name': 'Slovak', 'native_name': 'Slovenčina', 'is_rtl': False},
 {'code': 'slv', 'name': 'Slovenian', 'native_name': 'Slovenščina', 'is_rtl': False},
 {'code': 'sme', 'name': 'Northern Sami', 'native_name': 'Davvisámegiella', 'is_rtl': False},
 {'code': 'smo', 'name': 'Samoan', 'native_name': 'Gagana Samoa', 'is_rtl': False},
 {'code': 'sna', 'name': 'Shona', 'native_name': 'ChiShona', 'is_rtl': False},
 {'code': 'snd', 'name': 'Sindhi', 'native_name': 'سنڌي', 'is_rtl': True},
 {'code': 'som', 'name': 'Somali', 'native_name': 'Soomaaliga', 'is_rtl': False},
 {'code': 'sot', 'name': 'Southern Sotho', 'native_name': 'Sesotho', 'is_rtl': False},
 {'code': 'spa', 'name': 'Spanish', 'native_name': 'Español', 'is_rtl': False},
 {'code': 'sqi', 'name': 'Albanian', 'native_name': 'Shqip', 'is_rtl': False},
 {'code': 'srd', 'name': 'Sardinian', 'native_name': 'Sardu', 'is_rtl': False},
 {'code': 'srp', 'name': 'Serbian', 'native_name': 'Српски', 'is_rtl': False},
 {'code': 'ssw', 'name': 'Swati', 'native_name': 'SiSwati', 'is_rtl': False},
 {'code': 'sun', 'name': 'Sundanese', 'native_name': 'Basa Sunda', 'is_rtl': False},
 {'code': 'sux', 'name': 'Sumerian', 'native_name': None, 'is_rtl': False},
 {'code': 'swa', 'name': 'Swahili', 'native_name': 'Kiswahili', 'is_rtl': False},
 {'code': 'swe', 'name': 'Swedish', 'native_name': 'Svenska', 'is_rtl': False},
 {'code': 'tah', 'name': 'Tahitian', 'native_name': 'Reo Tahiti', 'is_rtl': False},
 {'code': 'tam', 'name': 'Tamil', 'native_name': 'தமிழ்', 'is_rtl': False},
 {'code': 'tat', 'name': 'Tatar', 'native_name': 'Татарча', 'is_rtl': False},
 {'code': 'tel', 'name': 'Telugu', 'native_name': 'తెలుగు', 'is_rtl': False},
 {'code': 'tgk', 'name': 'Tajik', 'native_name': 'Тоҷикӣ', 'is_rtl': False},
 {'code': 'tgl', 'name': 'Tagalog', 'native_name': 'Tagalog', 'is_rtl': False},
 {'code': 'tha', 'name': 'Thai', 'native_name': 'ไทย', 'is_rtl': False},
 {'code': 'tir', 'name': 'Tigrinya', 'native_name': 'ትግርኛ', 'is_rtl': False},
 {'code': 'ton', 'name': 'Tonga', 'native_name': 'Lea faka-Tonga', 'is_rtl': False},
 {'code': 'tsn', 'name': 'Tswana', 'native_name': 'Setswana', 'is_rtl': False},
 {'code': 'tso', 'name': 'Tsonga', 'native_name': 'XiTsonga', 'is_rtl': False},
 {'code': 'tuk', 'name': 'Turkmen', 'native_name': 'Türkmençe', 'is_rtl': False},
 {'code': 'tur', 'name': 'Turkish', 'native_name': 'Türkçe', 'is_rtl': False},
 {'code': 'twi', 'name': 'Twi', 'native_name': 'Twi', 'is_rtl': False},
 {'code': 'uig', 'name': 'Uighur', 'native_name': 'ئۇيغۇرچە', 'is_rtl': True},
 {'code': 'ukr', 'name': 'Ukrainian', 'native_name': 'Українська', 'is_rtl': False},
 {'code': 'urd', 'name': 'Urdu', 'native_name': 'اردو', 'is_rtl': True},
 {'code': 'uzb', 'name': 'Uzbek', 'native_name': 'Oʻzbekcha', 'is_rtl': False},
 {'code': 'ven', 'name': 'Venda', 'native_name': 'Tshivenḓa', 'is_rtl': False},
 {'code': 'vie', 'name': 'Vietnamese', 'native_name': 'Tiếng Việt', 'is_rtl': False},
 {'code': 'vol', 'name': 'Volapük', 'native_name': 'Volapük', 'is_rtl': False},
 {'code': 'wln', 'name': 'Walloon', 'native_name': 'Walon', 'is_rtl': False},
 {'code': 'wol', 'name': 'Wolof', 'native_name': 'Wolof', 'is_rtl': False},
 {'code': 'xho', 'name': 'Xhosa', 'native_name': 'IsiXhosa', 'is_rtl': False},
 {'code': 'yid', 'name': 'Yiddish', 'native_name': 'ייִדיש', 'is_rtl': True},
 {'code': 'yor', 'name': 'Yoruba', 'native_name': 'Yorùbá', 'is_rtl': False},
 {'code': 'zha', 'name': 'Zhuang', 'native_name': 'Saɯ cueŋƅ', 'is_rtl': False},
 {'code': 'zho', 'name': 'Chinese', 'native_name': '中文', 'is_rtl': False},
 {'code': 'zul', 'name': 'Zulu', 'native_name': 'IsiZulu', 'is_rtl': False}]
