"""create tables


Revision ID: b85d9c7efcf4
Revises: 
Create Date: 2026-05-03 15:06:13.267987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b85d9c7efcf4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('sort_name', sa.String(length=255), nullable=True),
    sa.Column('bio', sa.Text(), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('death_year', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authors_name'), 'authors', ['name'], unique=False)
    op.create_index(op.f('ix_authors_sort_name'), 'authors', ['sort_name'], unique=False)
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('first_published_year', sa.Integer(), nullable=True),
    sa.Column('work_type', sa.Enum('NOVEL', 'POEM', 'PLAY', 'EPIC', 'ESSAY', 'SHORT_STORY', 'COLLECTION', 'OTHER', name='work_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('languages',
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('native_name', sa.String(length=100), nullable=True),
    sa.Column('is_rtl', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('avatar_url', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('book_authors',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('AUTHOR', 'ATTRIBUTED_TO', 'TRANSLATOR', 'EDITOR', 'ILLUSTRATOR', 'INTRODUCTION', 'NARRATOR', 'COMPILER', 'OTHER', name='contributor_role'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'author_id', 'role')
    )
    op.create_table('book_covers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_covers_book_id'), 'book_covers', ['book_id'], unique=False)
    op.create_index('uq_book_covers_primary', 'book_covers', ['book_id'], unique=True, postgresql_where=sa.text('is_primary = true'))
    op.create_table('book_editions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('isbn_10', sa.String(length=10), nullable=True),
    sa.Column('isbn_13', sa.String(length=13), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('publication_date', sa.Date(), nullable=True),
    sa.Column('language_code', sa.String(length=3), nullable=True),
    sa.Column('format', sa.Enum('HARDCOVER', 'PAPERBACK', 'EBOOK', 'AUDIOBOOK', 'SERIAL', 'OTHER', name='edition_format'), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isbn_10'),
    sa.UniqueConstraint('isbn_13')
    )
    op.create_index(op.f('ix_book_editions_book_id'), 'book_editions', ['book_id'], unique=False)
    op.create_index(op.f('ix_book_editions_language_code'), 'book_editions', ['language_code'], unique=False)
    op.create_index(op.f('ix_book_editions_publisher'), 'book_editions', ['publisher'], unique=False)
    op.create_table('book_languages',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=3), nullable=False),
    sa.Column('role', sa.Enum('ORIGINAL', 'TRANSLATION', 'INCLUDED', name='language_role'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.PrimaryKeyConstraint('book_id', 'language_code', 'role')
    )
    op.create_index('ix_book_languages_language_code', 'book_languages', ['language_code'], unique=False)
    op.create_index('ix_book_languages_role', 'book_languages', ['role'], unique=False)
    op.create_table('book_titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('language_code', sa.String(length=3), nullable=False),
    sa.Column('title_type', sa.Enum('ORIGINAL', 'TRANSLATED', 'ALTERNATIVE', 'ROMANIZED', 'ABBREVIATION', name='title_type'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id', 'title', 'language_code', 'title_type', name='uq_book_title')
    )
    op.create_index(op.f('ix_book_titles_book_id'), 'book_titles', ['book_id'], unique=False)
    op.create_index(op.f('ix_book_titles_language_code'), 'book_titles', ['language_code'], unique=False)
    op.create_index(op.f('ix_book_titles_title'), 'book_titles', ['title'], unique=False)
    op.create_index('uq_book_titles_primary', 'book_titles', ['book_id'], unique=True, postgresql_where=sa.text('is_primary = true'))
    op.create_table('user_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('WANT_TO_READ', 'READING', 'READ', 'DNF', name='reading_status'), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('finished_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating IS NULL OR rating BETWEEN 1 AND 10', name='ck_user_book_rating_range'),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'book_id', name='uq_user_books_shelf_book')
    )
    op.create_index(op.f('ix_user_books_book_id'), 'user_books', ['book_id'], unique=False)
    op.create_index(op.f('ix_user_books_user_id'), 'user_books', ['user_id'], unique=False)
    op.create_table('edition_contributors',
    sa.Column('edition_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('AUTHOR', 'ATTRIBUTED_TO', 'TRANSLATOR', 'EDITOR', 'ILLUSTRATOR', 'INTRODUCTION', 'NARRATOR', 'COMPILER', 'OTHER', name='edition_contributor_role'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['edition_id'], ['book_editions.id'], ),
    sa.PrimaryKeyConstraint('edition_id', 'author_id', 'role')
    )
    op.create_table('edition_covers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edition_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['edition_id'], ['book_editions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edition_covers_edition_id'), 'edition_covers', ['edition_id'], unique=False)
    op.create_index('uq_edition_covers_primary', 'edition_covers', ['edition_id'], unique=True, postgresql_where=sa.text('is_primary = true'))
    op.create_table('edition_titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('edition_id', sa.Integer(), nullable=False),
    sa.Column('language_code', sa.String(length=3), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('title_type', sa.Enum('ORIGINAL', 'TRANSLATED', 'ALTERNATIVE', 'ROMANIZED', 'ABBREVIATION', name='title_type'), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['edition_id'], ['book_editions.id'], ),
    sa.ForeignKeyConstraint(['language_code'], ['languages.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_edition_titles_edition_id'), 'edition_titles', ['edition_id'], unique=False)
    op.create_index(op.f('ix_edition_titles_language_code'), 'edition_titles', ['language_code'], unique=False)
    op.create_index('uq_edition_titles_primary', 'edition_titles', ['edition_id'], unique=True, postgresql_where=sa.text('is_primary = true'))
    op.create_table('user_book_editions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_book_id', sa.Integer(), nullable=False),
    sa.Column('edition_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('WANT_TO_READ', 'READING', 'READ', 'DNF', name='reading_status'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['edition_id'], ['book_editions.id'], ),
    sa.ForeignKeyConstraint(['user_book_id'], ['user_books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_book_editions_edition_id'), 'user_book_editions', ['edition_id'], unique=False)
    op.create_index(op.f('ix_user_book_editions_user_book_id'), 'user_book_editions', ['user_book_id'], unique=False)
    op.create_index('uq_user_book_editions_no_edition', 'user_book_editions', ['user_book_id'], unique=True, postgresql_where=sa.text('edition_id IS NULL'))
    op.create_index('uq_user_book_editions_with_edition', 'user_book_editions', ['user_book_id', 'edition_id'], unique=True, postgresql_where=sa.text('edition_id IS NOT NULL'))
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_book_id', sa.Integer(), nullable=False),
    sa.Column('user_book_edition_id', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('contains_spoilers', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating IS NULL OR rating BETWEEN 1 AND 10', name='ck_review_rating_range'),
    sa.ForeignKeyConstraint(['user_book_edition_id'], ['user_book_editions.id'], ),
    sa.ForeignKeyConstraint(['user_book_id'], ['user_books.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reviews_user_book_edition_id'), 'reviews', ['user_book_edition_id'], unique=False)
    op.create_index(op.f('ix_reviews_user_book_id'), 'reviews', ['user_book_id'], unique=False)
    op.create_table('review_votes',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_helpful', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('review_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_votes')
    op.drop_index(op.f('ix_reviews_user_book_id'), table_name='reviews')
    op.drop_index(op.f('ix_reviews_user_book_edition_id'), table_name='reviews')
    op.drop_table('reviews')
    op.drop_index('uq_user_book_editions_with_edition', table_name='user_book_editions', postgresql_where=sa.text('edition_id IS NOT NULL'))
    op.drop_index('uq_user_book_editions_no_edition', table_name='user_book_editions', postgresql_where=sa.text('edition_id IS NULL'))
    op.drop_index(op.f('ix_user_book_editions_user_book_id'), table_name='user_book_editions')
    op.drop_index(op.f('ix_user_book_editions_edition_id'), table_name='user_book_editions')
    op.drop_table('user_book_editions')
    op.drop_index('uq_edition_titles_primary', table_name='edition_titles', postgresql_where=sa.text('is_primary = true'))
    op.drop_index(op.f('ix_edition_titles_language_code'), table_name='edition_titles')
    op.drop_index(op.f('ix_edition_titles_edition_id'), table_name='edition_titles')
    op.drop_table('edition_titles')
    op.drop_index('uq_edition_covers_primary', table_name='edition_covers', postgresql_where=sa.text('is_primary = true'))
    op.drop_index(op.f('ix_edition_covers_edition_id'), table_name='edition_covers')
    op.drop_table('edition_covers')
    op.drop_table('edition_contributors')
    op.drop_index(op.f('ix_user_books_user_id'), table_name='user_books')
    op.drop_index(op.f('ix_user_books_book_id'), table_name='user_books')
    op.drop_table('user_books')
    op.drop_index('uq_book_titles_primary', table_name='book_titles', postgresql_where=sa.text('is_primary = true'))
    op.drop_index(op.f('ix_book_titles_title'), table_name='book_titles')
    op.drop_index(op.f('ix_book_titles_language_code'), table_name='book_titles')
    op.drop_index(op.f('ix_book_titles_book_id'), table_name='book_titles')
    op.drop_table('book_titles')
    op.drop_index('ix_book_languages_role', table_name='book_languages')
    op.drop_index('ix_book_languages_language_code', table_name='book_languages')
    op.drop_table('book_languages')
    op.drop_index(op.f('ix_book_editions_publisher'), table_name='book_editions')
    op.drop_index(op.f('ix_book_editions_language_code'), table_name='book_editions')
    op.drop_index(op.f('ix_book_editions_book_id'), table_name='book_editions')
    op.drop_table('book_editions')
    op.drop_index('uq_book_covers_primary', table_name='book_covers', postgresql_where=sa.text('is_primary = true'))
    op.drop_index(op.f('ix_book_covers_book_id'), table_name='book_covers')
    op.drop_table('book_covers')
    op.drop_table('book_authors')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('languages')
    op.drop_table('books')
    op.drop_index(op.f('ix_authors_sort_name'), table_name='authors')
    op.drop_index(op.f('ix_authors_name'), table_name='authors')
    op.drop_table('authors')
    # ### end Alembic commands ###
